"""empty message

Revision ID: 95d06483f69d
Revises: 0053ab6fbcd8
Create Date: 2021-03-07 03:06:03.651906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d06483f69d'
down_revision = '0053ab6fbcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('user_email', sa.Integer(), nullable=True))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_email'], ['email'])
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'mail')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.add_column('orders', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'user_email')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
